# Generated by Django 4.0.6 on 2022-08-07 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Datcarta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('Cedula', models.FloatField()),
                ('Fecha_de_Ingreso', models.CharField(max_length=50)),
                ('Cargo', models.CharField(max_length=50)),
                ('Salario', models.FloatField()),
                ('Tipo_de_contrato', models.CharField(max_length=50)),
                ('is_active', models.BooleanField()),
            ],
        ),
    ]
